### ISSUE TITLE
Rename?

### ISSUE THREAD

**Issue by pattyland** [Marmelatze/avea_node#8]
This repository is called avea_node
In npm it's called avea_bulb

So for example in https://github.com/Alblahm/avea_node/blob/master/accessories/Sample_1Avea_EN_accessory.js you should embed this as avea_node
While in your repository https://github.com/Marmelatze/avea_server you require avea_bulb

I was having a hard time to understand that this is the same stuff but different names and branches. 

What should this repository be called? I will try to create pull requests on the other repositories so they all use the name!

Greets, Sören

**Comment by Marmelatze** [comment]
Sorry for the confusion. I renamed it.

**Comment by pattyland** [comment]
Great! Now we can shorten a few tutorials, the installation via npm is much easier
